### ISSUE TITLE
两张图有问题呢

### ISSUE THREAD

**Issue by MIFind** [ExcellentJR/mpvue-banner#1]

**Comment by ExcellentJR** [comment]
你是指什么问题？是这个例子里面的图没显示还是显示出来的样式有问题？

**Comment by MIFind** [comment]
> 你是指什么问题？是这个例子里面的图没显示还是显示出来的样式有问题？
样式问题。

**Comment by ExcellentJR** [comment]
@MIFind 这个插件的样式是需要自己调的，小于三张图就会出现样式上的问题，需要自己计算下修改一下数值
