### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by solarhell** [ExcellentJR/mpvue-banner#2]
https://github.com/ExcellentJR/mpvue-banner/blob/3a434eff27d717a6d323d94ace621a0411666500/src/pages/index/index.vue#L24

您好，这里的三目运算没能看懂，可以详细描述下吗？
或者可以利用这个能力吗？https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/observer.html
谢谢！

**Comment by ExcellentJR** [comment]
不好意思啊，这里的三目运算确实没说明，其实是为了让每项banner都根据自己所处的序列，得到其具体应该展现的样式，有的应该居中，有的应该靠右等等，而且当banner有两个和多个的时候，情况还不一样，所以才写的这么麻烦

**Comment by ExcellentJR** [comment]
@solarhell 你提到的这个能力，因为我用的是mpvue，基本采用的是vue的方式，所以直接用watch应该就行了，如果你想用原生的去改造的话，那样式上应该是类似的，然后你想说的可能是：能不能采用数据监听变化的方式来对其进行样式上处理？监听currentIndex的变化是可以的，但是这里没法监听bannerIndex，因为这是每个banner在所有banner中的序列是固定的

**Comment by solarhell** [comment]
@ExcellentJR 感谢回复！ 发现确实是小程序模板能力的限制。 尝试传一个函数来处理 `style` 的拼接。发现无法将 `wx:for` 内部的 `index` 传入这个函数。
